package com.example.model

/**
 * Device role separation.
 * The Parent device is the administrator/controller.
 * The Child device is the monitored device and ONLY media source.
 */
enum class DeviceRole {
    PARENT,
    CHILD
}

/**
 * Signaling protocol message types for Parent-Child coordination.
 */
enum class SignalingType {
    PAIR_REQUEST,
    PAIR_ACCEPTED,
    DEVICE_ONLINE,
    DEVICE_OFFLINE,
    START_SCREEN,
    STOP_SCREEN,
    START_CAMERA,
    STOP_CAMERA,
    SWITCH_CAMERA,
    START_AUDIO,
    STOP_AUDIO,
    SESSION_CREATED,
    WEBRTC_OFFER,
    WEBRTC_ANSWER,
    ICE_CANDIDATE,
    SESSION_ENDED,
    HEARTBEAT,
    SCREEN_PERMISSION_REQUIRED,
    SCREEN_PERMISSION_GRANTED,
    SCREEN_PERMISSION_DENIED,
    CAMERA_PERMISSION_REQUIRED,
    CAMERA_PERMISSION_GRANTED,
    CAMERA_PERMISSION_DENIED,
    AUDIO_PERMISSION_REQUIRED,
    AUDIO_PERMISSION_GRANTED,
    AUDIO_PERMISSION_DENIED,
    ALERT_CHILD_PROMPT,
    RESTART_ICE,
    FORCE_RELAY_MODE,
    ACK,
    RECONNECT
}

/**
 * Secure signaling message envelope.
 * Strictly guarantees messages route between the correct parent and child devices.
 */
data class SignalingMessage(
    val pairingId: String = "",
    val sessionId: String = "",
    val negotiationId: String = "",
    val senderDeviceId: String,
    val targetDeviceId: String,
    val messageId: String = "",
    val messageType: SignalingType,
    val payload: String = "",
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Single-use secure temporary OTP generated by Child device and registered with backend.
 */
data class OtpRecord(
    val code: String,
    val childDeviceId: String = "",
    val childDeviceName: String = "",
    val childModel: String = "",
    val parentAccountId: String = "",
    val parentDeviceId: String = "",
    val createdAt: Long = System.currentTimeMillis(),
    val expiresAt: Long,
    val isUsed: Boolean = false
) {
    val isExpired: Boolean
        get() = System.currentTimeMillis() > expiresAt
}

/**
 * Active binding record between Parent account/device and Child device.
 */
data class PairingRecord(
    val pairingId: String,
    val parentAccountId: String,
    val parentDeviceId: String,
    val childDeviceId: String,
    val childDeviceName: String,
    val childModel: String,
    val createdAt: Long = System.currentTimeMillis(),
    val lastSeen: Long = System.currentTimeMillis(),
    val isOnline: Boolean = false,
    val batteryPct: Int = 0,
    val isCharging: Boolean = false,
    val isScreenAuthorized: Boolean = false
)

/**
 * Binding verification states for Parent's "Check Binding Status".
 */
enum class BindingStatusState {
    CONNECTED_ONLINE,
    PAIRED_OFFLINE,
    NOT_PAIRED,
    INVALID_OTP,
    EXPIRED_OTP,
    CONNECTION_LOST,
    CHECKING
}

data class BindingStatusResult(
    val state: BindingStatusState,
    val message: String,
    val pairing: PairingRecord? = null
)

/**
 * Real-time child telemetry transmitted periodically to backend.
 */
data class ChildTelemetry(
    val childDeviceId: String,
    val deviceModel: String,
    val manufacturer: String,
    val androidVersion: String,
    val batteryPercentage: Int,
    val isCharging: Boolean,
    val isOnline: Boolean,
    val lastSeen: Long = System.currentTimeMillis(),
    val isScreenAuthorized: Boolean = false
)
